GET http://localhost:5000 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjU1MDQxNDAsInN1YiI6IjFhZmE4MjBiLWY3OWItNDZlYi1hOWQzLWVmNjE4OTFlYTUwMSJ9.9GrED1FqYxU6cslds9bs75f8x1oXK8FrQ8DncHfOl7c

###
POST http://localhost:5000/api/v1/cpfValidator HTTP/1.1
Content-Type: application/json

{
  "cpf_number": "503.278.618-79"
}

###

POST http://localhost:5000/api/v1/savecpf HTTP/1.1
Content-Type: application/json

{
  "name": "Matheus",
  "city":"Cajati",
  "state":"São Paulo",
  "cpfNumber": [5, 0, 3, 2, 7, 8, 6, 1, 8, 7, 9]
}

###