GET http://localhost:5000 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjU1MDQxNDAsInN1YiI6IjFhZmE4MjBiLWY3OWItNDZlYi1hOWQzLWVmNjE4OTFlYTUwMSJ9.9GrED1FqYxU6cslds9bs75f8x1oXK8FrQ8DncHfOl7c


// CPF
###
POST http://localhost:5000/api/v1/cpfValidator HTTP/1.1
Content-Type: application/json

{
  "cpf_number": "503.278.618-78"
}

###

POST http://localhost:5000/api/v1/savecpf HTTP/1.1
Content-Type: application/json

{
  "name": "Matheus Lemos",
  "city":"Curitiba",
  "state":"PR",
  "cpfNumber": "503.278.618-78"
}

###

GET http://localhost:5000/api/v1/cpfs HTTP/1.1

###

GET http://localhost:5000/api/v1/cpf/503.278.618-78 HTTP/1.1

###

PUT http://localhost:5000/api/v1/cpf/503.278.618-78 HTTP/1.1
Content-Type: application/json

{
  "name": "Matheus Henrique",
  "city": "Registro",
  "state": "São Paulo"
}

###

PUT http://localhost:5000/api/v1/addblocklistcpf/503.278.618-78 HTTP/1.1
Content-Type: application/json

###

PUT http://localhost:5000/api/v1/removeblocklistcpf/684.451.111-55 HTTP/1.1
Content-Type: application/json

###

Get http://localhost:5000/api/v1/blocklistcpfs HTTP/1.1
Content-Type: application/json

###

DELETE http://localhost:5000/api/v1/cpf/253.325.658-79 HTTP/1.1

###

//CNPJ

POST http://localhost:5000/api/v1/cnpjValidator HTTP/1.1
Content-Type: application/json

{
  "cnpj_number": "03.086.811/0001-45"
}

###

POST http://localhost:5000/api/v1/savecnpj HTTP/1.1
Content-Type: application/json

{
  "name": "Matheus",
  "city":"Cajati",
  "state":"São Paulo",
  "cnpjNumber": "03.086.811/0001-45"
}

###

GET http://localhost:5000/api/v1/cnpjs HTTP/1.1

###

GET http://localhost:5000/api/v1/cnpj/503.278.618-78 HTTP/1.1

###

PUT http://localhost:5000/api/v1/cnpj/503.278.618-78 HTTP/1.1
Content-Type: application/json

{
  "name": "Matheus Henrique Corp",
  "city": "Registro",
  "state": "São Paulo"
}

###
//Server

GET http://localhost:5000/api/v1/server-info HTTP/1.1

###

