GET  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjU1MDQxNDAsInN1YiI6IjFhZmE4MjBiLWY3OWItNDZlYi1hOWQzLWVmNjE4OTFlYTUwMSJ9.9GrED1FqYxU6cslds9bs75f8x1oXK8FrQ8DncHfOl7c


// CPF
###
POST /api/v1/cpfValidator HTTP/1.1
Content-Type: application/json

{
  "cpf_number": ""
}

###

POST /api/v1/savecpf HTTP/1.1
Content-Type: application/json

{
  "name": "Matheus Lemos",
  "city":"Curitiba",
  "state":"PR",
  "cpfNumber": ""
}

###

GET /api/v1/cpfs HTTP/1.1

###

GET /api/v1/cpf/503.278.618-78 HTTP/1.1

###

PUT /api/v1/cpf/503.278.618-78 HTTP/1.1
Content-Type: application/json

{
  "name": "Matheus Henrique",
  "city": "Curitiba",
  "state": "PR"
}

###

PUT /api/v1/addblocklistcpf/{numerodecpf} HTTP/1.1
Content-Type: application/json

###

PUT /api/v1/removeblocklistcpf/{numerodecpf} HTTP/1.1
Content-Type: application/json

###

Get /api/v1/blocklistcpfs HTTP/1.1
Content-Type: application/json

###

DELETE /api/v1/cpf/{numerodecpf} HTTP/1.1

###

//CNPJ

POST /api/v1/cnpjValidator HTTP/1.1
Content-Type: application/json

{
  "cnpj_number": "{numerodecnpj}"
}

###

POST /api/v1/savecnpj HTTP/1.1
Content-Type: application/json

{
  "name": "Matheus",
  "city":"Cajati",
  "state":"São Paulo",
  "cnpjNumber": "{numerodecnpj}"
}

###

GET /api/v1/cnpjs HTTP/1.1

###

GET /api/v1/cnpj/{numerodecnpj(lembrar de adicionar %2f caso utilize /)} HTTP/1.1

###

PUT /api/v1/cnpj/{numerodecnpj(lembrar de adicionar %2f caso utilize /)} HTTP/1.1
Content-Type: application/json

{
  "name": "Matheus Henrique Corp",
  "city": "Registro",
  "state": "São Paulo"
}
###
DELETE  /api/v1/cnpj/{numerodecnpj(lembrar de adicionar %2f caso utilize /)} HTTP/1.1
Content-Type: application/json
###

PUT /api/v1/addblocklistcnpj/{numerodecnpj(lembrar de adicionar %2f caso utilize /)} HTTP/1.1
Content-Type: application/json

###

PUT /api/v1/removeblocklistcnpj/{numerodecnpj(lembrar de adicionar %2f caso utilize /)} HTTP/1.1
Content-Type: application/json

###

Get /api/v1/blocklistcnpjs HTTP/1.1
Content-Type: application/json

###
//Server

GET /api/v1/server-info HTTP/1.1

###


